# -*- coding: utf-8 -*-
"""Pro latest 2 x With out SMOTE Model Training with modification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_uswgkTyuCN7MpDcQSQAOcq69C6NdOGy

**Install required packages**
"""

# Install required packages (if not already present)
!pip install -q tensorflow scikit-learn matplotlib seaborn

"""**Import libraries**"""

# Import standard libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Import machine learning and preprocessing libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, classification_report,
    roc_curve, precision_recall_curve
)

# Import deep learning libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, optimizers, losses, callbacks
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import (
    Dense, Input, Dropout, LSTM, Bidirectional,
    RepeatVector, TimeDistributed, Flatten, Reshape
)

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

print("✅ Libraries imported successfully!")
print(f"TensorFlow version: {tf.__version__}")
print(f"Keras version: {keras.__version__}")

from google.colab import drive
drive.mount('/content/drive')

"""**Load preprocessed data from Google *Drive* working directory**"""

# =============================================================================
# DATA LOADING WITH ORIGINAL TEST SET (IMBALANCED)
# =============================================================================

# Define path to preprocessed data
data_path = "/content/drive/MyDrive/Aklilu MSc. Thesis/Dataset/Preprocessed/NSL-KDD/80 20 Pro latest Preprosessed NSL-KDD Dataset with modification/"

# Load training and validation data (normal samples only)
X_train_norm = np.load(data_path + 'X_train_norm.npy')          # 52,580 samples
X_train_norm_seq = np.load(data_path + 'X_train_norm_seq.npy')  # 52,571 sequences
X_val_norm = np.load(data_path + 'X_val_norm.npy')              # 13,145 samples
X_val_norm_seq = np.load(data_path + 'X_val_norm_seq.npy')      # 13,136 sequences

# Load original (imbalanced) test set features and labels
X_test_orig = np.load(data_path + 'X_test.npy')                 # 21,796 samples
y_test_orig = np.load(data_path + 'y_test.npy')                 # 21,796 labels

# Load original test sequences (for LSTM/BiLSTM models)
X_test_seq_orig = np.load(data_path + 'X_test_seq.npy')         # 21,787 sequences
y_test_seq_orig = np.load(data_path + 'y_test_seq.npy')         # 21,787 labels

# Feature names (optional)
feature_names = np.load(data_path + 'feature_names.npy', allow_pickle=True)

# =============================================================================
# DATASET INFORMATION
# =============================================================================
print("="*60)
print("DATASET INFORMATION (ORIGINAL TEST SET)")
print("="*60)
print(f"X_train_norm (Standard AE):        {X_train_norm.shape}")
print(f"X_train_norm_seq (LSTM/BiLSTM):    {X_train_norm_seq.shape}")
print(f"X_val_norm (Standard AE):          {X_val_norm.shape}")
print(f"X_val_norm_seq (LSTM/BiLSTM):      {X_val_norm_seq.shape}")
print(f"X_test_orig (Standard AE):         {X_test_orig.shape}")
print(f"y_test_orig:                       {y_test_orig.shape}")
print(f"X_test_seq_orig (LSTM/BiLSTM):     {X_test_seq_orig.shape}")
print(f"y_test_seq_orig:                   {y_test_seq_orig.shape}")

print("\n" + "="*60)
print("ADDITIONAL DATASET STATISTICS")
print("="*60)
train_normal_count = X_train_norm.shape[0] + X_val_norm.shape[0]
print(f"Training samples (normal only):      {train_normal_count:,}")
print(f"Test samples (original imbalanced):  {X_test_orig.shape[0]:,}")

norm_count = np.sum(y_test_orig == 0)
att_count = np.sum(y_test_orig == 1)
print("\nClass distribution in original test set:")
print(f"  Normal:  {norm_count:,} samples ({norm_count/len(y_test_orig)*100:.1f}%)")
print(f"  Attack:  {att_count:,} samples ({att_count/len(y_test_orig)*100:.1f}%)")
print(f"  Attack percentage: {att_count/len(y_test_orig)*100:.2f}%")

# Verify sequence alignment
print(f"\nSequence alignment: Test sequences = {X_test_seq_orig.shape[0]}, labels = {y_test_seq_orig.shape[0]} (should match)")
print(f"Expected: {X_test_orig.shape[0] - 10 + 1} = {X_test_orig.shape[0] - 9} sequences")
print("="*60)

"""**DATA EXPLORATION AND VISUALIZATION**"""

# =============================================================================
# DATA EXPLORATION AND VISUALIZATION (Original Test Set Only)
# =============================================================================

# 1. Feature Distributions: Normal vs Attack (using original test set)
plt.figure(figsize=(15, 10))

# Plot distribution of first 9 features from test set
for i in range(9):
    plt.subplot(3, 3, i+1)

    # Get feature values for normal and attack classes
    normal_vals = X_test_orig[y_test_orig == 0, i]
    attack_vals = X_test_orig[y_test_orig == 1, i]

    # Plot histograms
    plt.hist(normal_vals, bins=30, alpha=0.5, label='Normal', density=True)
    plt.hist(attack_vals, bins=30, alpha=0.5, label='Attack', density=True)
    plt.title(f'Feature {i+1} Distribution')
    plt.legend(loc='upper right')
    plt.tight_layout()

plt.suptitle('Feature Distributions: Normal vs Attack (Original Test Set)', fontsize=16, y=1.02)
plt.show()


# 2. Class Distribution in Original Test Set
plt.figure(figsize=(8, 6))
class_counts = pd.Series(y_test_orig).value_counts()
bars = plt.bar(['Normal', 'Attack'], class_counts.values, color=['#2ecc71', '#e74c3c'])
plt.title('Class Distribution in Original Test Set (Imbalanced)', fontsize=14, fontweight='bold')
plt.ylabel('Number of Samples', fontsize=12)
plt.xlabel('Class', fontsize=12)
for i, count in enumerate(class_counts.values):
    plt.text(i, count + 200, f'{count:,}', ha='center', fontsize=12, fontweight='bold')
plt.grid(axis='y', alpha=0.3)
plt.show()


# 3. Feature Correlation Matrix (First 20 Features from Training Normal Data)
plt.figure(figsize=(12, 10))
correlation_matrix = pd.DataFrame(X_train_norm[:20, :20]).corr()
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, square=True, cbar_kws={"shrink": 0.8})
plt.title('Feature Correlation Matrix (First 20 Features) – Training Normal Data', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()


# 4. STACKED BAR CHART: Complete Dataset Composition (Training, Validation, and Original Test Set)
import matplotlib.pyplot as plt
import numpy as np

# Data from preprocessing (no SMOTE)
train_normal = 52580
val_normal = 13145
test_normal_orig = 9622
test_attack_orig = 12174

# Setup for stacked bar chart (original test set only)
categories = ['Training Set', 'Validation Set', 'Original Test Set\n(Imbalanced)']
normal_values = [train_normal, val_normal, test_normal_orig]
attack_values = [0, 0, test_attack_orig]
total_values = [train_normal, val_normal, test_normal_orig + test_attack_orig]

# Create figure with two subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle('NSL-KDD Dataset Composition: Training, Validation, and Test Sets',
             fontsize=16, fontweight='bold', y=1.02)

# ===== LEFT: STACKED BAR CHART (Absolute Values) =====
x = np.arange(len(categories))
width = 0.65

# Plot stacked bars
bars1 = ax1.bar(x, normal_values, width, label='Normal', color='#2ecc71', edgecolor='white', linewidth=1)
bars2 = ax1.bar(x, attack_values, width, bottom=normal_values, label='Attack', color='#e74c3c', edgecolor='white', linewidth=1)

# Add value labels on bars
for i, (normal, attack, total) in enumerate(zip(normal_values, attack_values, total_values)):
    # Normal segment label
    if normal > 0:
        ax1.text(i, normal/2, f'{normal:,}', ha='center', va='center',
                fontweight='bold', fontsize=9, color='white')
    # Attack segment label
    if attack > 0:
        ax1.text(i, normal + attack/2, f'{attack:,}', ha='center', va='center',
                fontweight='bold', fontsize=9, color='white')
    # Total label on top
    ax1.text(i, total + 500, f'Total: {total:,}', ha='center', va='bottom',
            fontweight='bold', fontsize=9, color='black')

# Customize left chart
ax1.set_ylabel('Number of Samples', fontsize=12, fontweight='bold')
ax1.set_xticks(x)
ax1.set_xticklabels(categories, fontsize=10, fontweight='bold')
ax1.set_title('Dataset Composition (Absolute Values)', fontsize=13, fontweight='bold', pad=10)
ax1.legend(loc='upper right', fontsize=10)
ax1.grid(axis='y', alpha=0.3, linestyle='--')
ax1.set_ylim(0, 65000)

# Add percentage labels on top of training/validation bars
ax1.text(0, train_normal + 1500, '100% Normal', ha='center', va='bottom',
        fontsize=9, fontstyle='italic', color='#27ae60')
ax1.text(1, val_normal + 1500, '100% Normal', ha='center', va='bottom',
        fontsize=9, fontstyle='italic', color='#27ae60')

# ===== RIGHT: STACKED BAR CHART (Percentage Distribution) =====
# Calculate percentages
normal_pct = [100, 100,
              test_normal_orig/(test_normal_orig + test_attack_orig)*100]
attack_pct = [0, 0,
              test_attack_orig/(test_normal_orig + test_attack_orig)*100]

# Plot percentage stacked bars
bars1 = ax2.bar(x, normal_pct, width, label='Normal %', color='#2ecc71', edgecolor='white', linewidth=1)
bars2 = ax2.bar(x, attack_pct, width, bottom=normal_pct, label='Attack %', color='#e74c3c', edgecolor='white', linewidth=1)

# Add percentage labels
for i, (n_pct, a_pct) in enumerate(zip(normal_pct, attack_pct)):
    if n_pct > 0:
        ax2.text(i, n_pct/2, f'{n_pct:.1f}%', ha='center', va='center',
                fontweight='bold', fontsize=10, color='white')
    if a_pct > 0:
        ax2.text(i, n_pct + a_pct/2, f'{a_pct:.1f}%', ha='center', va='center',
                fontweight='bold', fontsize=10, color='white')

# Customize right chart
ax2.set_ylabel('Percentage (%)', fontsize=12, fontweight='bold')
ax2.set_xticks(x)
ax2.set_xticklabels(categories, fontsize=10, fontweight='bold')
ax2.set_title('Dataset Composition (Percentage Distribution)', fontsize=13, fontweight='bold', pad=10)
ax2.legend(loc='upper right', fontsize=10)
ax2.grid(axis='y', alpha=0.3, linestyle='--')
ax2.set_ylim(0, 100)

plt.tight_layout()
plt.show()


# 5. Print numerical summary (original test set only)
print("\n" + "="*70)
print("NSL-KDD DATASET SUMMARY AFTER PREPROCESSING")
print("="*70)
print(f"{'Dataset Component':<30} {'Normal':>12} {'Attack':>12} {'Total':>12} {'Normal %':>12}")
print("-"*70)
print(f"{'Training Set':<30} {train_normal:>12,} {'0':>12} {train_normal:>12,} {'100.0%':>12}")
print(f"{'Validation Set':<30} {val_normal:>12,} {'0':>12} {val_normal:>12,} {'100.0%':>12}")
print(f"{'Original Test Set':<30} {test_normal_orig:>12,} {test_attack_orig:>12,} {test_normal_orig + test_attack_orig:>12,} {test_normal_orig/(test_normal_orig+test_attack_orig)*100:>11.1f}%")
print("="*70)
print("\nNote: The original test set is imbalanced (no SMOTE applied).")

"""**DATA EXPLORATION AND VISUALIZATION 2**"""

# =============================================================================
# DATA EXPLORATION AND VISUALIZATION - PART 2 (Original Test Set Only)
# =============================================================================

import matplotlib.pyplot as plt
import numpy as np

# Data from preprocessing (no SMOTE)
train_normal = 52580
val_normal = 13145
test_normal_orig = 9622
test_attack_orig = 12174

# Create figure with subplots
fig = plt.figure(figsize=(14, 8))
fig.suptitle('NSL-KDD Dataset Characteristics After Preprocessing', fontsize=18, fontweight='bold', y=1.02)

# 1. Training/Validation Split (Pie Chart)
ax1 = plt.subplot(2, 2, 1)
sizes = [train_normal, val_normal]
labels = ['Training Set\n(Normal Only)', 'Validation Set\n(Normal Only)']
colors = ['#2ecc71', '#3498db']
explode = (0.05, 0)
wedges, texts, autotexts = plt.pie(sizes, explode=explode, labels=labels, colors=colors,
                                    autopct='%1.1f%%', startangle=90, shadow=True)
for autotext in autotexts:
    autotext.set_fontweight('bold')
    autotext.set_color('white')
plt.title('Training/Validation Split\n(80% / 20%)', fontsize=12, fontweight='bold')

# 2. Original Test Set Distribution (Bar Chart)
ax2 = plt.subplot(2, 2, 2)
x_pos = [0, 1]
heights = [test_normal_orig, test_attack_orig]
bars = plt.bar(x_pos, heights, color=['#2ecc71', '#e74c3c'], width=0.6, edgecolor='black', linewidth=1)
plt.xticks(x_pos, ['Normal', 'Attack'], fontsize=11, fontweight='bold')
plt.ylabel('Number of Samples', fontsize=11, fontweight='bold')
plt.title('Original Test Set\n(Imbalanced - 21,796 samples)', fontsize=12, fontweight='bold')
for bar, height in zip(bars, heights):
    plt.text(bar.get_x() + bar.get_width()/2, height + 200, f'{height:,}',
             ha='center', fontsize=10, fontweight='bold')
plt.grid(axis='y', alpha=0.3, linestyle='--')

# 3. Dataset Composition Overview (Horizontal Bar)
ax3 = plt.subplot(2, 2, 3)
categories = ['Training Set\n(Normal)', 'Validation Set\n(Normal)',
              'Test Set\n(Normal)', 'Test Set\n(Attack)']
values = [train_normal, val_normal, test_normal_orig, test_attack_orig]
colors_list = ['#2ecc71', '#3498db', '#2ecc71', '#e74c3c']
y_pos = np.arange(len(categories))
bars = ax3.barh(y_pos, values, color=colors_list, edgecolor='black', linewidth=0.5)
ax3.set_yticks(y_pos)
ax3.set_yticklabels(categories, fontsize=9, fontweight='bold')
ax3.set_xlabel('Number of Samples', fontsize=11, fontweight='bold')
ax3.set_title('Complete Dataset Composition', fontsize=12, fontweight='bold')
ax3.grid(axis='x', alpha=0.3, linestyle='--')
for i, (bar, val) in enumerate(zip(bars, values)):
    ax3.text(val + 300, bar.get_y() + bar.get_height()/2, f'{val:,}',
             va='center', fontsize=9, fontweight='bold')

# 4. Summary Statistics Table
ax4 = plt.subplot(2, 2, 4)
ax4.axis('tight')
ax4.axis('off')
table_data = [
    ['Dataset Component', 'Normal', 'Attack', 'Total'],
    ['Training Set', f'{train_normal:,}', '0', f'{train_normal:,}'],
    ['Validation Set', f'{val_normal:,}', '0', f'{val_normal:,}'],
    ['Original Test Set', f'{test_normal_orig:,}', f'{test_attack_orig:,}', f'{test_normal_orig + test_attack_orig:,}']
]
table = ax4.table(cellText=table_data, loc='center', cellLoc='center', colWidths=[0.28, 0.2, 0.2, 0.2])
table.auto_set_font_size(False)
table.set_fontsize(9)
table.scale(1.2, 1.5)
for (i, j), cell in table.get_celld().items():
    if i == 0:
        cell.set_facecolor('#34495e')
        cell.set_text_props(weight='bold', color='white')
    elif i % 2 == 0:
        cell.set_facecolor('#f2f2f2')
    cell.set_edgecolor('black')
    cell.set_linewidth(0.5)
ax4.set_title('Dataset Summary Statistics', fontsize=12, fontweight='bold', pad=20)

plt.tight_layout()
plt.show()

# ============================================================
# Numerical Summary (Original Test Set Only)
# ============================================================
print("\n" + "="*70)
print("NSL-KDD DATASET SUMMARY AFTER PREPROCESSING")
print("="*70)
print(f"{'Dataset Component':<30} {'Normal':>12} {'Attack':>12} {'Total':>12} {'Normal %':>12}")
print("-"*70)
print(f"{'Training Set':<30} {train_normal:>12,} {'0':>12} {train_normal:>12,} {'100.0%':>12}")
print(f"{'Validation Set':<30} {val_normal:>12,} {'0':>12} {val_normal:>12,} {'100.0%':>12}")
print(f"{'Original Test Set':<30} {test_normal_orig:>12,} {test_attack_orig:>12,} {test_normal_orig + test_attack_orig:>12,} {test_normal_orig/(test_normal_orig+test_attack_orig)*100:>11.1f}%")
print("="*70)
print("\nNote: No SMOTE was applied to the test set. The original imbalanced distribution is preserved.")

"""**Define Standard Autoencoder Architecture**"""

def build_standard_ae(input_dim, latent_dim=8):
    input_layer = Input(shape=(input_dim,))
    # Encoder
    x = Dense(32, activation='relu', kernel_regularizer=keras.regularizers.l2(0.001))(input_layer)
    x = Dense(16, activation='relu')(x)
    latent = Dense(latent_dim, activation='relu', name='latent')(x)
    # Decoder
    x = Dense(16, activation='relu')(latent)
    x = Dense(32, activation='relu')(x)
    output = Dense(input_dim, activation='linear')(x)

    autoencoder = Model(input_layer, output, name='Standard_Autoencoder')
    autoencoder.compile(optimizer=optimizers.Adam(learning_rate=0.001),
                        loss='mse', metrics=['mae'])
    encoder = Model(input_layer, latent, name='Encoder')
    return autoencoder, encoder

input_dim = X_train_norm.shape[1]
print(f"Input dimension: {input_dim}")
ae_model, ae_encoder = build_standard_ae(input_dim=input_dim, latent_dim=8)
ae_model.summary()

"""*Train Standard Autoencoder*"""

print("\n" + "="*50)
print("TRAINING STANDARD AUTOENCODER")
print("="*50)

early_stop = callbacks.EarlyStopping(monitor='val_loss', patience=10,
                                      min_delta=0.0001, restore_best_weights=True, verbose=1)
reduce_lr = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                                         patience=5, min_lr=1e-6, verbose=1)

history_ae = ae_model.fit(
    X_train_norm, X_train_norm,
    validation_data=(X_val_norm, X_val_norm),
    epochs=100,
    batch_size=64,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

"""*Evaluate Standard Autoencoder Training*"""

# Plot training and validation loss curves
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Loss plot
axes[0].plot(history_ae.history['loss'], label='Training Loss', linewidth=2)
axes[0].plot(history_ae.history['val_loss'], label='Validation Loss', linewidth=2)
axes[0].set_title('Standard Autoencoder: Training and Validation Loss', fontsize=12)
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss (MSE)')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# MAE plot
axes[1].plot(history_ae.history['mae'], label='Training MAE', linewidth=2)
axes[1].plot(history_ae.history['val_mae'], label='Validation MAE', linewidth=2)
axes[1].set_title('Standard Autoencoder: Training and Validation MAE', fontsize=12)
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('MAE')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Print final loss values
print(f"Final Training Loss:   {history_ae.history['loss'][-1]:.6f}")
print(f"Final Validation Loss: {history_ae.history['val_loss'][-1]:.6f}")

"""*Anomaly Detection with Standard Autoencoder*"""

def compute_reconstruction_errors(model, data, is_sequence=False):
    """Return MSE per sample (for standard AE) or per sequence (for LSTM models)."""
    preds = model.predict(data, verbose=0)
    if is_sequence:
        errors = np.mean(np.square(data - preds), axis=(1,2))
    else:
        errors = np.mean(np.square(data - preds), axis=1)
    return errors

def percentile_threshold(errors, percentile=95):
    return np.percentile(errors, percentile)

def evaluate_model(y_true, y_pred, errors, model_name):
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    auc = roc_auc_score(y_true, errors)
    print(f"\n{model_name} Performance:")
    print(f"  Accuracy:  {acc:.4f}")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall:    {rec:.4f}")
    print(f"  F1-Score:  {f1:.4f}")
    print(f"  AUC-ROC:   {auc:.4f}")
    return {'accuracy': acc, 'precision': prec, 'recall': rec, 'f1': f1, 'auc': auc}

# Compute reconstruction errors on validation set (normal only)
val_errors_ae = compute_reconstruction_errors(ae_model, X_val_norm, is_sequence=False)

# Set threshold at 95th percentile of validation errors
percentile = 95
threshold_ae = percentile_threshold(val_errors_ae, percentile)
print(f"Standard AE threshold ({percentile}th percentile): {threshold_ae:.6f}")

# Evaluate on the original (imbalanced) test set
test_errors_ae = compute_reconstruction_errors(ae_model, X_test_orig, is_sequence=False)
y_pred_ae = (test_errors_ae > threshold_ae).astype(int)

# Calculate metrics
metrics_ae = evaluate_model(y_test_orig, y_pred_ae, test_errors_ae, "Standard AE (Original Test Set)")

# Confusion matrix
cm_ae = confusion_matrix(y_test_orig, y_pred_ae)
plt.figure(figsize=(5,4))
sns.heatmap(cm_ae, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Normal','Attack'], yticklabels=['Normal','Attack'])
plt.title('Standard AE Confusion Matrix (Original Test Set)', fontsize=12)
plt.show()

"""*Reconstruction Error Distribution for Standard AE*"""

plt.figure(figsize=(10,6))
plt.hist(test_errors_ae[y_test_orig == 0], bins=50, alpha=0.7, label='Normal', color='green', density=True)
plt.hist(test_errors_ae[y_test_orig == 1], bins=50, alpha=0.7, label='Attack', color='red', density=True)
plt.axvline(threshold_ae, color='blue', linestyle='--', linewidth=2, label=f'Threshold: {threshold_ae:.4f}')
plt.xlabel('Reconstruction Error (MSE)', fontsize=12)
plt.ylabel('Density', fontsize=12)
plt.title('Standard AE: Reconstruction Error Distribution (Original Test Set)', fontsize=14)
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""**Define LSTM Autoencoder Architecture**"""

def build_lstm_ae(sequence_shape, latent_dim=8):
    timesteps, features = sequence_shape
    input_layer = Input(shape=(timesteps, features))
    # Encoder
    x = LSTM(32, activation='tanh', return_sequences=True, dropout=0.2)(input_layer)
    x = LSTM(16, activation='tanh', return_sequences=False, dropout=0.2)(x)
    latent = Dense(latent_dim, activation='relu', name='latent')(x)
    # Decoder
    x = RepeatVector(timesteps)(latent)
    x = LSTM(16, activation='tanh', return_sequences=True, dropout=0.2)(x)
    x = LSTM(32, activation='tanh', return_sequences=True, dropout=0.2)(x)
    output = TimeDistributed(Dense(features, activation='linear'))(x)

    autoencoder = Model(input_layer, output, name='LSTM_Autoencoder')
    autoencoder.compile(optimizer=optimizers.Adam(learning_rate=0.001),
                        loss='mse', metrics=['mae'])
    # Encoder model for latent space (optional)
    encoder = Model(input_layer, latent, name='LSTM_Encoder')
    return autoencoder, encoder

sequence_shape = X_train_norm_seq.shape[1:]  # (10, 38)
print(f"Sequence shape: {sequence_shape}")
lstm_model, lstm_encoder = build_lstm_ae(sequence_shape)
lstm_model.summary()

"""*Train LSTM Autoencoder*"""

print("\n" + "="*50)
print("TRAINING LSTM AUTOENCODER")
print("="*50)

early_stop = callbacks.EarlyStopping(monitor='val_loss', patience=10,
                                      min_delta=0.0001, restore_best_weights=True, verbose=1)

history_lstm = lstm_model.fit(
    X_train_norm_seq, X_train_norm_seq,
    validation_data=(X_val_norm_seq, X_val_norm_seq),
    epochs=100,
    batch_size=64,
    callbacks=[early_stop],
    verbose=1
)

"""*Evaluate LSTM Autoencoder Training*"""

# Plot training and validation loss curves
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Loss plot
axes[0].plot(history_lstm.history['loss'], label='Training Loss', linewidth=2)
axes[0].plot(history_lstm.history['val_loss'], label='Validation Loss', linewidth=2)
axes[0].set_title('LSTM Autoencoder: Training and Validation Loss', fontsize=12)
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss (MSE)')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# MAE plot
axes[1].plot(history_lstm.history['mae'], label='Training MAE', linewidth=2)
axes[1].plot(history_lstm.history['val_mae'], label='Validation MAE', linewidth=2)
axes[1].set_title('LSTM Autoencoder: Training and Validation MAE', fontsize=12)
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('MAE')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Print final loss values
print(f"Final Training Loss:   {history_lstm.history['loss'][-1]:.6f}")
print(f"Final Validation Loss: {history_lstm.history['val_loss'][-1]:.6f}")

"""*Anomaly Detection with LSTM Autoencoder*"""

# Compute reconstruction errors on validation sequences (normal only)
val_errors_lstm = compute_reconstruction_errors(lstm_model, X_val_norm_seq, is_sequence=True)
threshold_lstm = percentile_threshold(val_errors_lstm, percentile)
print(f"LSTM AE threshold ({percentile}th percentile): {threshold_lstm:.6f}")

# Evaluate on the original (imbalanced) test sequences
test_errors_lstm = compute_reconstruction_errors(lstm_model, X_test_seq_orig, is_sequence=True)
y_pred_lstm = (test_errors_lstm > threshold_lstm).astype(int)

metrics_lstm = evaluate_model(y_test_seq_orig, y_pred_lstm, test_errors_lstm, "LSTM AE (Original Test Set)")

# Confusion matrix
cm_lstm = confusion_matrix(y_test_seq_orig, y_pred_lstm)
plt.figure(figsize=(5,4))
sns.heatmap(cm_lstm, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Normal','Attack'], yticklabels=['Normal','Attack'])
plt.title('LSTM AE Confusion Matrix (Original Test Set)', fontsize=12)
plt.show()

"""*Reconstruction Error Distribution for LSTM‑AE*"""

# ==================== Reconstruction Error Distribution: LSTM AE ====================
plt.figure(figsize=(10,6))
plt.hist(test_errors_lstm[y_test_seq_orig == 0], bins=50, alpha=0.7, label='Normal', color='green', density=True)
plt.hist(test_errors_lstm[y_test_seq_orig == 1], bins=50, alpha=0.7, label='Attack', color='red', density=True)
plt.axvline(threshold_lstm, color='blue', linestyle='--', linewidth=2, label=f'Threshold: {threshold_lstm:.4f}')
plt.xlabel('Reconstruction Error (MSE)', fontsize=12)
plt.ylabel('Density', fontsize=12)
plt.title('LSTM AE: Reconstruction Error Distribution (Original Test Set)', fontsize=14)
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""**Define BiLSTM Autoencoder Architecture**"""

def build_bilstm_ae(sequence_shape, latent_dim=8):
    timesteps, features = sequence_shape
    input_layer = Input(shape=(timesteps, features))
    # Encoder
    x = Bidirectional(LSTM(32, activation='tanh', return_sequences=True, dropout=0.2),
                      merge_mode='concat')(input_layer)
    x = Dropout(0.2)(x)
    x = Bidirectional(LSTM(16, activation='tanh', return_sequences=False, dropout=0.2),
                      merge_mode='concat')(x)
    x = Dropout(0.2)(x)
    latent = Dense(latent_dim, activation='relu', name='latent')(x)
    # Decoder
    x = RepeatVector(timesteps)(latent)
    x = Bidirectional(LSTM(16, activation='tanh', return_sequences=True, dropout=0.2),
                      merge_mode='concat')(x)
    x = Dropout(0.2)(x)
    x = Bidirectional(LSTM(32, activation='tanh', return_sequences=True, dropout=0.2),
                      merge_mode='concat')(x)
    x = Dropout(0.2)(x)
    output = TimeDistributed(Dense(features, activation='linear'))(x)

    autoencoder = Model(input_layer, output, name='BiLSTM_Autoencoder')
    autoencoder.compile(optimizer=optimizers.Adam(learning_rate=0.001),
                        loss='mse', metrics=['mae'])
    encoder = Model(input_layer, latent, name='BiLSTM_Encoder')
    return autoencoder, encoder

bilstm_model, bilstm_encoder = build_bilstm_ae(sequence_shape)
bilstm_model.summary()

"""*Train BiLSTM Autoencoder*"""

print("\n" + "="*50)
print("TRAINING BIDIRECTIONAL LSTM AUTOENCODER")
print("="*50)

history_bilstm = bilstm_model.fit(
    X_train_norm_seq, X_train_norm_seq,
    validation_data=(X_val_norm_seq, X_val_norm_seq),
    epochs=100,
    batch_size=64,
    callbacks=[early_stop],
    verbose=1
)

"""*Evaluate BiLSTM Autoencoder Training*"""

fig, axes = plt.subplots(1, 2, figsize=(12,4))
axes[0].plot(history_bilstm.history['loss'], label='Train')
axes[0].plot(history_bilstm.history['val_loss'], label='Val')
axes[0].set_title('BiLSTM AE Loss')
axes[0].legend()
axes[1].plot(history_bilstm.history['mae'], label='Train')
axes[1].plot(history_bilstm.history['val_mae'], label='Val')
axes[1].set_title('BiLSTM AE MAE')
axes[1].legend()
plt.show()

print("Final Training Loss: {:.6f}".format(history_bilstm.history['loss'][-1]))
print("Final Validation Loss: {:.6f}".format(history_bilstm.history['val_loss'][-1]))

"""*Anomaly Detection with BiLSTM Autoencoder*"""

# Compute reconstruction errors on validation sequences (normal only)
val_errors_bilstm = compute_reconstruction_errors(bilstm_model, X_val_norm_seq, is_sequence=True)
threshold_bilstm = percentile_threshold(val_errors_bilstm, percentile)
print(f"BiLSTM AE threshold ({percentile}th percentile): {threshold_bilstm:.6f}")

# Evaluate on the original (imbalanced) test sequences
test_errors_bilstm = compute_reconstruction_errors(bilstm_model, X_test_seq_orig, is_sequence=True)
y_pred_bilstm = (test_errors_bilstm > threshold_bilstm).astype(int)

metrics_bilstm = evaluate_model(y_test_seq_orig, y_pred_bilstm, test_errors_bilstm, "BiLSTM AE (Original Test Set)")

# Confusion matrix
cm_bilstm = confusion_matrix(y_test_seq_orig, y_pred_bilstm)
plt.figure(figsize=(5,4))
sns.heatmap(cm_bilstm, annot=True, fmt='d', cmap='Purples',
            xticklabels=['Normal','Attack'], yticklabels=['Normal','Attack'])
plt.title('BiLSTM AE Confusion Matrix (Original Test Set)', fontsize=12)
plt.show()

"""*Reconstruction Error Distribution for BiLSTM‑AE*"""

plt.figure(figsize=(10,6))
plt.hist(test_errors_bilstm[y_test_seq_orig == 0], bins=50, alpha=0.7, label='Normal', color='green', density=True)
plt.hist(test_errors_bilstm[y_test_seq_orig == 1], bins=50, alpha=0.7, label='Attack', color='red', density=True)
plt.axvline(threshold_bilstm, color='blue', linestyle='--', linewidth=2, label=f'Threshold: {threshold_bilstm:.4f}')
plt.xlabel('Reconstruction Error (MSE)', fontsize=12)
plt.ylabel('Density', fontsize=12)
plt.title('BiLSTM AE: Reconstruction Error Distribution (Original Test Set)', fontsize=14)
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""**COMPARATIVE ANALYSIS OF MODELS**

*Comparative Reconstruction Error Distributions for All Models*
"""

# ==================== Comparative Reconstruction Error Distributions ====================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Standard AE (using original test set)
axes[0].hist(test_errors_ae[y_test_orig == 0], bins=50, alpha=0.7, label='Normal', color='green', density=True)
axes[0].hist(test_errors_ae[y_test_orig == 1], bins=50, alpha=0.7, label='Attack', color='red', density=True)
axes[0].axvline(threshold_ae, color='blue', linestyle='--', linewidth=2, label=f'Thresh: {threshold_ae:.3f}')
axes[0].set_title('Standard AE', fontsize=14)
axes[0].set_xlabel('MSE', fontsize=12)
axes[0].set_ylabel('Density', fontsize=12)
axes[0].legend()
axes[0].grid(alpha=0.3)

# LSTM AE (using original test sequences)
axes[1].hist(test_errors_lstm[y_test_seq_orig == 0], bins=50, alpha=0.7, label='Normal', color='green', density=True)
axes[1].hist(test_errors_lstm[y_test_seq_orig == 1], bins=50, alpha=0.7, label='Attack', color='red', density=True)
axes[1].axvline(threshold_lstm, color='blue', linestyle='--', linewidth=2, label=f'Thresh: {threshold_lstm:.3f}')
axes[1].set_title('LSTM AE', fontsize=14)
axes[1].set_xlabel('MSE', fontsize=12)
axes[1].set_ylabel('Density', fontsize=12)
axes[1].legend()
axes[1].grid(alpha=0.3)

# BiLSTM AE (using original test sequences)
axes[2].hist(test_errors_bilstm[y_test_seq_orig == 0], bins=50, alpha=0.7, label='Normal', color='green', density=True)
axes[2].hist(test_errors_bilstm[y_test_seq_orig == 1], bins=50, alpha=0.7, label='Attack', color='red', density=True)
axes[2].axvline(threshold_bilstm, color='blue', linestyle='--', linewidth=2, label=f'Thresh: {threshold_bilstm:.3f}')
axes[2].set_title('BiLSTM AE', fontsize=14)
axes[2].set_xlabel('MSE', fontsize=12)
axes[2].set_ylabel('Density', fontsize=12)
axes[2].legend()
axes[2].grid(alpha=0.3)

plt.suptitle('Comparative Reconstruction Error Distributions: Normal vs. Attack', fontsize=16)
plt.tight_layout()
plt.show()

"""*COMPARATIVE ANALYSIS OF MODELS*"""

# Gather metrics
accuracy_ae = metrics_ae['accuracy']
precision_ae = metrics_ae['precision']
recall_ae = metrics_ae['recall']
f1_ae = metrics_ae['f1']
auc_ae = metrics_ae['auc']

accuracy_lstm = metrics_lstm['accuracy']
precision_lstm = metrics_lstm['precision']
recall_lstm = metrics_lstm['recall']
f1_lstm = metrics_lstm['f1']
auc_lstm = metrics_lstm['auc']

accuracy_bilstm = metrics_bilstm['accuracy']
precision_bilstm = metrics_bilstm['precision']
recall_bilstm = metrics_bilstm['recall']
f1_bilstm = metrics_bilstm['f1']
auc_bilstm = metrics_bilstm['auc']

# Create comparison DataFrame
comparison_data = {
    'Model': ['Standard AE', 'LSTM AE', 'BiLSTM AE'],
    'Accuracy': [accuracy_ae, accuracy_lstm, accuracy_bilstm],
    'Precision': [precision_ae, precision_lstm, precision_bilstm],
    'Recall': [recall_ae, recall_lstm, recall_bilstm],
    'F1-Score': [f1_ae, f1_lstm, f1_bilstm],
    'AUC-ROC': [auc_ae, auc_lstm, auc_bilstm],
    'Threshold': [threshold_ae, threshold_lstm, threshold_bilstm]
}

comparison_df = pd.DataFrame(comparison_data)
print("\n" + "="*70)
print("COMPARATIVE PERFORMANCE OF AUTOENCODER MODELS")
print("="*70)
print(comparison_df.to_string(index=False))

# Plot comparative performance
fig = plt.figure(figsize=(16, 12))

# Accuracy comparison
ax1 = plt.subplot(2, 2, 1)
bars1 = ax1.bar(comparison_df['Model'], comparison_df['Accuracy'],
                color=['blue', 'orange', 'purple'])
ax1.set_title('Model Accuracy Comparison', fontsize=14)
ax1.set_ylabel('Accuracy', fontsize=12)
ax1.set_ylim([0, 1.05])
for i, v in enumerate(comparison_df['Accuracy']):
    ax1.text(i, v + 0.02, f'{v:.4f}', ha='center', fontsize=10, fontweight='bold')

# F1-Score comparison
ax2 = plt.subplot(2, 2, 2)
bars2 = ax2.bar(comparison_df['Model'], comparison_df['F1-Score'],
                color=['blue', 'orange', 'purple'])
ax2.set_title('Model F1-Score Comparison', fontsize=14)
ax2.set_ylabel('F1-Score', fontsize=12)
ax2.set_ylim([0, 1.05])
for i, v in enumerate(comparison_df['F1-Score']):
    ax2.text(i, v + 0.02, f'{v:.4f}', ha='center', fontsize=10, fontweight='bold')

# AUC-ROC comparison
ax3 = plt.subplot(2, 2, 3)
bars3 = ax3.bar(comparison_df['Model'], comparison_df['AUC-ROC'],
                color=['blue', 'orange', 'purple'])
ax3.set_title('Model AUC-ROC Comparison', fontsize=14)
ax3.set_ylabel('AUC-ROC', fontsize=12)
ax3.set_ylim([0, 1.05])
for i, v in enumerate(comparison_df['AUC-ROC']):
    ax3.text(i, v + 0.02, f'{v:.4f}', ha='center', fontsize=10, fontweight='bold')

# Radar chart for multi-metric comparison
ax4 = plt.subplot(2, 2, 4, projection='polar')
categories = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'AUC-ROC']
N = len(categories)
angles = [n / float(N) * 2 * np.pi for n in range(N)]
angles += angles[:1]

ax4.set_theta_offset(np.pi / 2)
ax4.set_theta_direction(-1)
plt.xticks(angles[:-1], categories, fontsize=10)

colors = ['blue', 'orange', 'purple']
for idx, model in enumerate(comparison_df['Model']):
    values = comparison_df.loc[idx, categories].values.flatten().tolist()
    values += values[:1]
    ax4.plot(angles, values, linewidth=2, linestyle='solid', label=model, color=colors[idx])
    ax4.fill(angles, values, alpha=0.1, color=colors[idx])

ax4.set_title('Multi-Metric Model Comparison', fontsize=14, y=1.1)
ax4.legend(loc='upper right', bbox_to_anchor=(1.3, 1.0))
plt.tight_layout()
plt.show()

# Print best model based on F1-Score
best_model_idx = comparison_df['F1-Score'].idxmax()
best_model = comparison_df.loc[best_model_idx, 'Model']
best_f1 = comparison_df.loc[best_model_idx, 'F1-Score']

print("\n" + "="*60)
print("BEST MODEL SELECTION")
print("="*60)
print(f"Based on F1-Score, the best performing model is: {best_model}")
print(f"With F1-Score: {best_f1:.4f}")
print("\nModel Performance Ranking (by F1-Score):")
print(comparison_df.sort_values('F1-Score', ascending=False)[['Model', 'F1-Score']].to_string(index=False))

# Additional analysis: Confusion matrices comparison
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Standard AE confusion matrix
sns.heatmap(cm_ae, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Normal', 'Attack'], yticklabels=['Normal', 'Attack'], ax=axes[0])
axes[0].set_title(f'Standard AE\nAccuracy: {accuracy_ae:.4f}, F1: {f1_ae:.4f}')
axes[0].set_ylabel('True Label')
axes[0].set_xlabel('Predicted Label')

# LSTM AE confusion matrix
sns.heatmap(cm_lstm, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Normal', 'Attack'], yticklabels=['Normal', 'Attack'], ax=axes[1])
axes[1].set_title(f'LSTM AE\nAccuracy: {accuracy_lstm:.4f}, F1: {f1_lstm:.4f}')
axes[1].set_ylabel('True Label')
axes[1].set_xlabel('Predicted Label')

# BiLSTM AE confusion matrix
sns.heatmap(cm_bilstm, annot=True, fmt='d', cmap='Purples',
            xticklabels=['Normal', 'Attack'], yticklabels=['Normal', 'Attack'], ax=axes[2])
axes[2].set_title(f'BiLSTM AE\nAccuracy: {accuracy_bilstm:.4f}, F1: {f1_bilstm:.4f}')
axes[2].set_ylabel('True Label')
axes[2].set_xlabel('Predicted Label')

plt.tight_layout()
plt.show()

print("\n✅ All model metrics have been updated with improved thresholds!")

"""*ROC Curves for All Models*"""

# ==================== ROC Curves for All Models ====================
from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(8, 6))

# Standard AE (original test set)
fpr_ae, tpr_ae, _ = roc_curve(y_test_orig, test_errors_ae)
roc_auc_ae = auc(fpr_ae, tpr_ae)
plt.plot(fpr_ae, tpr_ae, label=f'Standard AE (AUC = {roc_auc_ae:.3f})', linewidth=2)

# LSTM AE (original test sequences)
fpr_lstm, tpr_lstm, _ = roc_curve(y_test_seq_orig, test_errors_lstm)
roc_auc_lstm = auc(fpr_lstm, tpr_lstm)
plt.plot(fpr_lstm, tpr_lstm, label=f'LSTM AE (AUC = {roc_auc_lstm:.3f})', linewidth=2)

# BiLSTM AE (original test sequences)
fpr_bi, tpr_bi, _ = roc_curve(y_test_seq_orig, test_errors_bilstm)
roc_auc_bi = auc(fpr_bi, tpr_bi)
plt.plot(fpr_bi, tpr_bi, label=f'BiLSTM AE (AUC = {roc_auc_bi:.3f})', linewidth=2)

# Random guess line
plt.plot([0, 1], [0, 1], 'k--', label='Random', linewidth=1)

plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('ROC Curves for Autoencoder Models (Original Test Set)', fontsize=14)
plt.legend(loc='lower right')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""**MODEL INTERPRETATION AND VISUALIZATION**"""

# =============================================================================
# MODEL INTERPRETATION AND VISUALIZATION (Original Test Set)
# =============================================================================

# Visualize latent space representations (Standard AE only)
def visualize_latent_space(encoder, data, labels, model_name):
    """Visualize latent space representation in 2D using PCA"""
    # Get latent representations
    latent_repr = encoder.predict(data, verbose=0)

    # Apply PCA for visualization
    from sklearn.decomposition import PCA
    pca = PCA(n_components=2)
    latent_2d = pca.fit_transform(latent_repr)

    # Plot
    plt.figure(figsize=(10, 8))
    scatter = plt.scatter(latent_2d[:, 0], latent_2d[:, 1],
                         c=labels, cmap='viridis', alpha=0.6,
                         edgecolors='k', linewidth=0.5)
    plt.colorbar(scatter, label='Class (0=Normal, 1=Attack)')
    plt.title(f'{model_name}: Latent Space Visualization (PCA)', fontsize=14)
    plt.xlabel('PCA Component 1', fontsize=12)
    plt.ylabel('PCA Component 2', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

    # Calculate separation metric
    from sklearn.metrics import silhouette_score
    if len(set(labels)) > 1:
        sil_score = silhouette_score(latent_repr, labels)
        print(f"Silhouette Score for {model_name}: {sil_score:.4f}")

print("Standard AE Latent Space (original test set):")
visualize_latent_space(ae_encoder, X_test_orig, y_test_orig, "Standard AE")

# Visualize reconstruction examples
def visualize_reconstructions(model, data, n_examples=5, model_name="Model", is_sequence=False):
    """
    Visualize original vs reconstructed samples
    For sequence models, data is 3D; we flatten each example for plotting.
    """
    # Get reconstructions
    reconstructions = model.predict(data[:n_examples], verbose=0)

    fig, axes = plt.subplots(n_examples, 2, figsize=(12, 3*n_examples))

    for i in range(n_examples):
        # Original
        if is_sequence:
            orig = data[i].flatten()
            rec = reconstructions[i].flatten()
        else:
            orig = data[i]
            rec = reconstructions[i]

        axes[i, 0].plot(orig, 'b-', label='Original', linewidth=2)
        axes[i, 0].set_title(f'Example {i+1}: Original', fontsize=11)
        axes[i, 0].grid(True, alpha=0.3)

        axes[i, 1].plot(rec, 'r-', label='Reconstructed', linewidth=2)
        axes[i, 1].set_title(f'Example {i+1}: Reconstructed', fontsize=11)
        axes[i, 1].grid(True, alpha=0.3)

        error = np.mean(np.square(orig - rec))
        axes[i, 1].text(0.05, 0.95, f'MSE: {error:.4f}',
                       transform=axes[i, 1].transAxes,
                       verticalalignment='top',
                       bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    plt.suptitle(f'{model_name}: Original vs Reconstructed Features', fontsize=14, y=1.02)
    plt.tight_layout()
    plt.show()

print("\nStandard AE Reconstructions (original test set):")
visualize_reconstructions(ae_model, X_test_orig[:5], model_name="Standard AE", is_sequence=False)

print("\nLSTM AE Reconstructions (original test sequences):")
visualize_reconstructions(lstm_model, X_test_seq_orig[:5], model_name="LSTM AE", is_sequence=True)

print("\nBiLSTM AE Reconstructions (original test sequences):")
visualize_reconstructions(bilstm_model, X_test_seq_orig[:5], model_name="BiLSTM AE", is_sequence=True)

"""**MODEL SAVING AND DEPLOYMENT PREPARATION**"""

# Save all trained models
print("Saving trained models...")

# Standard AE
ae_model.save('standard_autoencoder_final.h5')
print("✓ Standard Autoencoder saved as 'standard_autoencoder_final.h5'")

# LSTM AE
lstm_model.save('lstm_autoencoder_final.h5')
print("✓ LSTM Autoencoder saved as 'lstm_autoencoder_final.h5'")

# BiLSTM AE
bilstm_model.save('bilstm_autoencoder_final.h5')
print("✓ BiLSTM Autoencoder saved as 'bilstm_autoencoder_final.h5'")

# Save thresholds for each model
thresholds = {
    'standard_ae_threshold': float(threshold_ae),
    'lstm_ae_threshold': float(threshold_lstm),
    'bilstm_ae_threshold': float(threshold_bilstm)
}

import json
with open('model_thresholds.json', 'w') as f:
    json.dump(thresholds, f, indent=4)
print("✓ Model thresholds saved as 'model_thresholds.json'")

# Save performance metrics
performance_metrics = comparison_df.to_dict(orient='records')
with open('model_performance.json', 'w') as f:
    json.dump(performance_metrics, f, indent=4)
print("✓ Performance metrics saved as 'model_performance.json'")

print("\n" + "="*60)
print("MODEL SAVING COMPLETE")
print("="*60)
print("All models and associated files have been saved successfully!")
print("\nFiles saved:")
print("1. standard_autoencoder_final.h5")
print("2. lstm_autoencoder_final.h5")
print("3. bilstm_autoencoder_final.h5")
print("4. model_thresholds.json")
print("5. model_performance.json")

"""**Final Summary**"""

print("\n" + "="*70)
print("THESIS MODEL DEVELOPMENT - FINAL SUMMARY")
print("="*70)
print("\nRESEARCH OBJECTIVES ACHIEVED:")
print("1. ✓ Developed three autoencoder variants for anomaly detection")
print("2. ✓ Implemented unsupervised learning on normal traffic only")
print("3. ✓ Evaluated models using NSL-KDD dataset")
print("4. ✓ Compared performance across different architectures")

best_row = comparison_df.loc[comparison_df['F1-Score'].idxmax()]
print(f"\nBEST PERFORMING MODEL: {best_row['Model']}")
print(f"  - Accuracy:  {best_row['Accuracy']:.4f}")
print(f"  - Precision: {best_row['Precision']:.4f}")
print(f"  - Recall:    {best_row['Recall']:.4f}")
print(f"  - F1-Score:  {best_row['F1-Score']:.4f}")
print(f"  - AUC-ROC:   {best_row['AUC-ROC']:.4f}")

print("\n" + "="*70)